// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALygq5TcCr-RQ6HKoahzrUdjys28SxV0w',
    appId: '1:442799979301:web:8de5a326a9b872310678cc',
    messagingSenderId: '442799979301',
    projectId: 'clone-of-spotify',
    authDomain: 'clone-of-spotify.firebaseapp.com',
    storageBucket: 'clone-of-spotify.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6QZAgHIHuVraR6mG7Q5PPO3kx4YphFdc',
    appId: '1:442799979301:android:59b433dc4e48a5880678cc',
    messagingSenderId: '442799979301',
    projectId: 'clone-of-spotify',
    storageBucket: 'clone-of-spotify.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnKZ6a6i1PUVV62kNkTUU_yA5BvlakQk4',
    appId: '1:442799979301:ios:47a6f025528dcf100678cc',
    messagingSenderId: '442799979301',
    projectId: 'clone-of-spotify',
    storageBucket: 'clone-of-spotify.appspot.com',
    iosBundleId: 'com.example.spotifyClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnKZ6a6i1PUVV62kNkTUU_yA5BvlakQk4',
    appId: '1:442799979301:ios:47a6f025528dcf100678cc',
    messagingSenderId: '442799979301',
    projectId: 'clone-of-spotify',
    storageBucket: 'clone-of-spotify.appspot.com',
    iosBundleId: 'com.example.spotifyClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALygq5TcCr-RQ6HKoahzrUdjys28SxV0w',
    appId: '1:442799979301:web:676f20ef2c61c2f80678cc',
    messagingSenderId: '442799979301',
    projectId: 'clone-of-spotify',
    authDomain: 'clone-of-spotify.firebaseapp.com',
    storageBucket: 'clone-of-spotify.appspot.com',
  );

}